

services:
  ticket_postgres:
    image: bitnami/postgresql:latest
    container_name: tickethub_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tickethub_db
    volumes:
      - postgres_data:/bitnami/postgresql

  ticket_cache:
    image: redis:7-alpine
    container_name: tickethub_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - redisdata:/data

volumes:
  postgres_data:
  redisdata: